######################################################################
# Automatically generated by qmake (2.01a) sam. nov. 3 19:44:05 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CLauncher.h
SOURCES += CLauncher.cpp main.cpp
